chore: build report

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,4 +45,10 @@ jobs:
         run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
 
       - name: VSTest
-        run: vstest.console.exe /Platform:x64 x64\Release\parser-tests.dll
+        run: vstest.console.exe /Platform:x64 x64\\${{ env.BUILD_CONFIGURATION }}\\parser-tests.dll /ResultsDirectory:test-results /Logger:trx
+
+      - uses: actions/upload-artifact@v4 # upload test results
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Test Results
+          path: test-results/**
